[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/femmes/equipe/"
to = "/equipe/"

[[redirects]]
from = "/lycee-odilon-redon/"
to = "/organisations/lycee-odilon-redon/"

[[redirects]]
from = "/femmes/lee-miller/"
to = "/les-femmes/lee-miller/"

[[redirects]]
from = "/baptiste-louis/"
to = "/equipe/baptiste-louis/"

[[redirects]]
from = "/femme-d/"
to = "/les-femmes/femme-d/"

[[redirects]]
from = "/femmes/camille-claudel/"
to = "/les-femmes/camille-claudel/"

[[redirects]]
from = "/a-propos/equipe/baptiste-louis/"
to = "/equipe/baptiste-louis/"

[[redirects]]
from = "/femmes/wangari-muta-maathai/"
to = "/les-femmes/wangari-muta-maathai/"

[[redirects]]
from = "/femmes/simone-veil/"
to = "/les-femmes/simone-veil/"

[[redirects]]
from = "/ar/"
to = "/les-femmes/alice-recoque/"

[[redirects]]
from = "/alice-recoque/"
to = "/les-femmes/alice-recoque/"

[[redirects]]
from = "/a-propos/organisations/universite-de-pau-et-des-pays-de-ladour/"
to = "/organisations/universite-de-pau-et-des-pays-de-ladour/"

[[redirects]]
from = "/hugo-mensah/"
to = "/equipe/hugo-mensah/"

[[redirects]]
from = "/a-propos/equipe-editoriale/"
to = "/equipe-editoriale/"

[[redirects]]
from = "/le-dispositif/"
to = "/mettre-en-place/"

[[redirects]]
from = "/informaticienne/"
to = "/metier/informaticienne/"

[[redirects]]
from = "/universite-de-pau-et-des-pays-de-ladour/"
to = "/organisations/universite-de-pau-et-des-pays-de-ladour/"

[[redirects]]
from = "/femmes/alice-recoque-1-1-1/"
to = "/les-femmes/winnie-mandela/"

[[redirects]]
from = "/nathan-vandaele/"
to = "/equipe/nathan-vandaele/"

[[redirects]]
from = "/femmes/alice-recoque-1/"
to = "/les-femmes/wangari-muta-maathai/"

[[redirects]]
from = "/a-propos/equipe/hugo-mensah/"
to = "/equipe/hugo-mensah/"

[[redirects]]
from = "/femmes/winnie-mandela/"
to = "/les-femmes/winnie-mandela/"

[[redirects]]
from = "/femmes/ellen-johnson-sirleaf/"
to = "/les-femmes/ellen-johnson-sirleaf/"

[[redirects]]
from = "/femmes/rosa-bonheur/"
to = "/les-femmes/rosa-bonheur/"

[[redirects]]
from = "/a-propos/plan-du-site/"
to = "/plan-du-site/"

[[redirects]]
from = "/femmes/gisele-halimi/"
to = "/les-femmes/gisele-halimi/"

[[redirects]]
from = "/a-propos/equipe/"
to = "/equipe/"

[[redirects]]
from = "/femmes/fatima-ouassak-1/"
to = "/les-femmes/rosa-bonheur/"

[[redirects]]
from = "/femmes/annie-ernaux/"
to = "/les-femmes/annie-ernaux/"

[[redirects]]
from = "/sciences-technologie-et-sante/"
to = "/domaine/sciences-technologie-et-sante/"

[[redirects]]
from = "/a-propos/organisations/cci-nouvelle-aquitaine/"
to = "/organisations/cci-nouvelle-aquitaine/"

[[redirects]]
from = "/femmes/katherine-johnson/"
to = "/les-femmes/katherine-johnson/"

[[redirects]]
from = "/femmes/delia-derbyshire/"
to = "/les-femmes/delia-derbyshire/"

[[redirects]]
from = "/femmes/judit-polgar/"
to = "/les-femmes/judit-polgar/"

[[redirects]]
from = "/violette-dorange/"
to = "/les-femmes/violette-dorange/"

[[redirects]]
from = "/loic-leforestier/"
to = "/equipe/loic-leforestier/"

[[redirects]]
from = "/a-propos/mentions-legales/"
to = "/mentions-legales/"

[[redirects]]
from = "/a-propos/actualites/"
to = "/actualites/"

[[redirects]]
from = "/ellen-johnson-sirleaf/"
to = "/les-femmes/ellen-johnson-sirleaf/"

[[redirects]]
from = "/a-propos/equipe/coralie-alexandru/"
to = "/equipe/coralie-alexandru/"

[[redirects]]
from = "/a-propos/equipe/line-cabaret/"
to = "/equipe/line-cabaret/"

[[redirects]]
from = "/femmes/itala-fulvia-villa/"
to = "/les-femmes/itala-fulvia-villa/"

[[redirects]]
from = "/a-propos/equipe/loic-leforestier/"
to = "/equipe/loic-leforestier/"

[[redirects]]
from = "/femmes/alice-recoque/"
to = "/les-femmes/alice-recoque/"

[[redirects]]
from = "/hl/"
to = "/les-femmes/hedy-lamarr/"

[[redirects]]
from = "/femmes/alice-recoque-1-1/"
to = "/les-femmes/ellen-johnson-sirleaf/"

[[redirects]]
from = "/delia-derbyshire/"
to = "/les-femmes/delia-derbyshire/"

[[redirects]]
from = "/a-propos/accessibilite/"
to = "/accessibilite/"

[[redirects]]
from = "/tom-detaevernier/"
to = "/equipe/tom-detaevernier/"

[[redirects]]
from = "/les-femmes/camille-claudel-1/"
to = "/les-femmes/ada-lovelace/"

[[redirects]]
from = "/aung-san-suu-kyi/"
to = "/les-femmes/aung-san-suu-kyi/"

[[redirects]]
from = "/metier/archiecte/"
to = "/metier/architecte/"

[[redirects]]
from = "/a-propos/politique-de-confidentialite/"
to = "/politique-de-confidentialite/"

[[redirects]]
from = "/a-propos/organisations/universite-de-bordeaux/"
to = "/organisations/universite-de-bordeaux/"

[[redirects]]
from = "/coralie-alexandru/"
to = "/equipe/coralie-alexandru/"

[[redirects]]
from = "/universite-de-bordeaux/"
to = "/organisations/universite-de-bordeaux/"

[[redirects]]
from = "/line-cabaret/"
to = "/equipe/line-cabaret/"

[[redirects]]
from = "/femmes/fatima-ouassak/"
to = "/les-femmes/fatima-ouassak/"

[[redirects]]
from = "/kathrine-switzer/"
to = "/les-femmes/kathrine-switzer/"

[[redirects]]
from = "/femmes/sarah-maldoror/"
to = "/les-femmes/sarah-maldoror/"

[[redirects]]
from = "/femmes/hedy-lamarr/"
to = "/les-femmes/hedy-lamarr/"

[[redirects]]
from = "/a-propos/equipe/emma-dimbour/"
to = "/equipe/emma-dimbour/"

[[redirects]]
from = "/femmes/aung-san-suu-kyi/"
to = "/les-femmes/aung-san-suu-kyi/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/equipe-editoriale/"

[[redirects]]
from = "/hedy-lamarr/"
to = "/les-femmes/hedy-lamarr/"

[[redirects]]
from = "/lettres-langues-et-arts/"
to = "/domaine/lettres-langues-et-arts/"

[[redirects]]
from = "/academie-de-bordeaux/"
to = "/organisations/academie-de-bordeaux/"

[[redirects]]
from = "/itala-fulvia-villa/"
to = "/les-femmes/itala-fulvia-villa/"

[[redirects]]
from = "/cci-nouvelle-aquitaine/"
to = "/organisations/cci-nouvelle-aquitaine/"

[[redirects]]
from = "/emma-dimbour/"
to = "/equipe/emma-dimbour/"

[[redirects]]
from = "/femmes/oumou-sangare/"
to = "/les-femmes/oumou-sangare/"

[[redirects]]
from = "/femmes/violette-dorange/"
to = "/les-femmes/violette-dorange/"

[[redirects]]
from = "/camille-claudel/"
to = "/les-femmes/camille-claudel/"

[[redirects]]
from = "/judit-polgar/"
to = "/les-femmes/judit-polgar/"

[[redirects]]
from = "/a-propos/equipe/lorenzo-le-roho/"
to = "/equipe/lorenzo-le-roho/"

[[redirects]]
from = "/a-propos/equipe/nathan-vandaele/"
to = "/equipe/nathan-vandaele/"

[[redirects]]
from = "/universite-bordeaux-montaigne/"
to = "/organisations/universite-bordeaux-montaigne/"

[[redirects]]
from = "/femmes/nomfemme/"
to = "/equipe/"

[[redirects]]
from = "/a-propos/organisations/academie-de-bordeaux/"
to = "/organisations/academie-de-bordeaux/"

[[redirects]]
from = "/femmes/francoise-barre-sinoussi/"
to = "/les-femmes/francoise-barre-sinoussi/"

[[redirects]]
from = "/femmes/jocelyn-bell-burnell/"
to = "/les-femmes/jocelyn-bell-burnell/"

[[redirects]]
from = "/a-propos/organisations/universite-bordeaux-montaigne/"
to = "/organisations/universite-bordeaux-montaigne/"

[[redirects]]
from = "/femmes/"
to = "/les-femmes/"

[[redirects]]
from = "/lorenzo-le-roho/"
to = "/equipe/lorenzo-le-roho/"

[[redirects]]
from = "/a-propos/organisations/"
to = "/organisations/"

[[redirects]]
from = "/femmes/genevieve-beney/"
to = "/les-femmes/aung-san-suu-kyi/"

[[redirects]]
from = "/femmes/kathrine-switzer/"
to = "/les-femmes/kathrine-switzer/"

[[redirects]]
from = "/a-propos/equipe/tom-detaevernier/"
to = "/equipe/tom-detaevernier/"

